const products = {
  success: true,
  data: [
    {
      page: 1,
      products: [
        {
          id: 1,
          name: "Product 1",
          price: 10.99,
          quantity: 100,
          url: "/images/products/1.jpg",
          img: "images/products/1.jpg",
          description: "This is product 1",
          category: "Category 1",
        },
        {
          id: 2,
          name: "Product 2",
          price: 12.99,
          quantity: 10,
          url: "images/products/2.jpg",
          img: "images/products/2.jpg",
          description: "This is product 2",
          category: "Category 1",
        },
        {
          id: 3,
          name: "Product 3",
          price: 13.99,
          quantity: 10,
          url: "images/products/3.jpg",
          img: "images/products/3.jpg",
          description: "This is product 3",
          category: "Category 1",
        },
        {
          id: 4,
          name: "Product 4",
          price: 10.99,
          quantity: 100,
          url: "images/products/4.jpg",
          img: "images/products/4.jpg",
          description: "This is product 4",
          category: "Category 1",
        },
        {
          id: 5,
          name: "Product 5",
          price: 15.99,
          quantity: 100,
          url: "images/products/5.jpg",
          img: "images/products/5.jpg",
          description: "This is product 5",
          category: "Category 1",
        },
        {
          id: 6,
          name: "Product 6",
          price: 16.99,
          quantity: 13,
          url: "images/products/6.jpg",
          img: "images/products/6.jpg",
          description: "This is product 6",
          category: "Category 1",
        },
        {
          id: 7,
          name: "Product 7",
          price: 17.99,
          quantity: 70,
          url: "images/products/7.jpg",
          img: "images/products/7.jpg",
          description: "This is product 7",
          category: "Category 1",
        },
        {
          id: 8,
          name: "Product 8",
          price: 18.99,
          quantity: 80,
          url: "images/products/8.jpg",
          img: "images/products/8.jpg",
          description: "This is product 8",
          category: "Category 1",
        },
        {
          id: 9,
          name: "Product 9",
          price: 19.99,
          quantity: 90,
          url: "images/products/9.jpg",
          img: "images/products/9.jpg",
          description: "This is product 9",
          category: "Category 1",
        },
        {
          id: 10,
          name: "Product 10",
          price: 100.99,
          quantity: 100,
          url: "images/products/10.jpg",
          img: "images/products/10.jpg",
          description: "This is product 10",
          category: "Category 1",
        },
        {
          id: 11,
          name: "Product 11",
          price: 110.99,
          quantity: 100,
          url: "images/products/11.jpg",
          img: "images/products/11.jpg",
          description: "This is product 11",
          category: "Category 1",
        },
        {
          id: 12,
          name: "Product 12",
          price: 120.99,
          quantity: 100,
          url: "images/products/12.jpg",
          img: "images/products/12.jpg",
          description: "This is product 12",
          category: "Category 1",
        },

        {
          id: 13,
          name: "Product 13",
          price: 130.99,
          quantity: 130,
          url: "images/products/13.jpg",
          img: "images/products/13.jpg",
          description: "This is product 13",
          category: "Category 3",
        },
        {
          id: 14,
          name: "Product 14",
          price: 140.99,
          quantity: 140,
          url: "images/products/14.jpg",
          img: "images/products/14.jpg",
          description: "This is product 14",
          category: "Category 4",
        },
        {
          id: 15,
          name: "Product 15",
          price: 150.99,
          quantity: 150,
          url: "images/products/15.jpg",
          img: "images/products/15.jpg",
          description: "This is product 15",
          category: "Category 3",
        },
        {
          id: 16,
          name: "Product 16,",
          price: 130.99,
          quantity: 130,
          url: "images/products/16.jpg",
          img: "images/products/16.jpg",
          description: "This is product 16",
          category: "Category 3",
        },
        {
          id: 17,
          name: "Product 17",
          price: 130.99,
          quantity: 130,
          url: "images/products/17.jpg",
          img: "images/products/17.jpg",
          description: "This is product 17",
          category: "Category 3",
        },
        {
          id: 18,
          name: "Product 18",
          price: 130.99,
          quantity: 130,
          url: "images/products/18.jpg",
          img: "images/products/18.jpg",
          description: "This is product 18",
          category: "Category 3",
        },
        {
          id: 19,
          name: "Product 19",
          price: 130.99,
          quantity: 130,
          url: "images/products/19.jpg",
          img: "images/products/19.jpg",
          description: "This is product 19",
          category: "Category 3",
        },
        {
          id: 20,
          name: "Product 20",
          price: 130.99,
          quantity: 130,
          url: "images/products/20.jpg",
          img: "images/products/20.jpg",
          description: "This is product 20",
          category: "Category 3",
        },
        {
          id: 21,
          name: "Product 21",
          price: 130.99,
          quantity: 130,
          url: "images/products/21.jpg",
          img: "images/products/21.jpg",
          description: "This is product 21",
          category: "Category 3",
        },
        {
          id: 22,
          name: "Product 22",
          price: 130.99,
          quantity: 130,
          url: "images/products/22.jpg",
          img: "images/products/22.jpg",
          description: "This is product 22",
          category: "Category 3",
        },
        {
          id: 23,
          name: "Product 23",
          price: 130.99,
          quantity: 130,
          url: "images/products/23.jpg",
          img: "images/products/23.jpg",
          description: "This is product 23",
          category: "Category 3",
        },
        {
          id: 24,
          name: "Product 24",
          price: 130.99,
          quantity: 130,
          url: "images/products/24.jpg",
          img: "images/products/24.jpg",
          description: "This is product 24",
          category: "Category 3",
        },
      ],
    },
  ],
};

export default products;
