const products = {
  success: true,
  data: [
    {
      page: 1,
      products: [
        {
          id: 1,
          name: "Product 1",
          price: 10.99,
          quantity: 100,
          url: "/images/products/1.jpg",
          img: "/images/1.jpg",
          description: "This is product 1",
          category: "Category 1",
        },
        {
          id: 2,
          name: "Product 2",
          price: 12.99,
          quantity: 10,
          url: "images/products/2.jpg",
          img: "/images/2.jpg",
          description: "This is product 2",
          category: "Category 1",
        },
        {
          id: 3,
          name: "Product 3",
          price: 13.99,
          quantity: 10,
          url: "images/products/3.jpg",
          img: "/images/3.jpg",
          description: "This is product 3",
          category: "Category 1",
        },
        {
          id: 4,
          name: "Product 4",
          price: 10.99,
          quantity: 100,
          url: "images/products/4.jpg",
          img: "/images/4.jpg",
          description: "This is product 4",
          category: "Category 1",
        },
        {
          id: 5,
          name: "Product 5",
          price: 15.99,
          quantity: 100,
          url: "images/products/5.jpg",
          img: "/images/5.jpg",
          description: "This is product 5",
          category: "Category 1",
        },
        {
          id: 6,
          name: "Product 6",
          price: 16.99,
          quantity: 13,
          url: "images/products/6.jpg",
          img: "/images/6.jpg",
          description: "This is product 6",
          category: "Category 1",
        },
        {
          id: 7,
          name: "Product 7",
          price: 17.99,
          quantity: 70,
          url: "images/products/7.jpg",
          img: "/images/7.jpg",
          description: "This is product 7",
          category: "Category 1",
        },
        {
          id: 8,
          name: "Product 8",
          price: 18.99,
          quantity: 80,
          url: "images/products/8.jpg",
          img: "/images/8.jpg",
          description: "This is product 8",
          category: "Category 1",
        },
        {
          id: 9,
          name: "Product 9",
          price: 19.99,
          quantity: 90,
          url: "images/products/9.jpg",
          img: "/images/9.jpg",
          description: "This is product 9",
          category: "Category 1",
        },
        {
          id: 10,
          name: "Product 10",
          price: 100.99,
          quantity: 100,
          url: "images/products/10.jpg",
          img: "/images/10.jpg",
          description: "This is product 10",
          category: "Category 1",
        },
        {
          id: 11,
          name: "Product 11",
          price: 110.99,
          quantity: 100,
          url: "images/products/11.jpg",
          img: "/images/11.jpg",
          description: "This is product 11",
          category: "Category 1",
        },
        {
          id: 12,
          name: "Product 12",
          price: 120.99,
          quantity: 100,
          url: "images/products/12.jpg",
          img: "/images/12.jpg",
          description: "This is product 12",
          category: "Category 1",
        },

        {
          id: 13,
          name: "Product 13",
          price: 130.99,
          quantity: 130,
          url: "images/products/13.jpg",
          img: "/images/23.jpg",
          description: "This is product 13",
          category: "Category 3",
        },
        {
          id: 14,
          name: "Product 14",
          price: 140.99,
          quantity: 140,
          url: "images/products/14.jpg",
          img: "/images/14.jpg",
          description: "This is product 14",
          category: "Category 4",
        },
        {
          id: 15,
          name: "Product 15",
          price: 150.99,
          quantity: 150,
          url: "images/products/15.jpg",
          img: "/images/15.jpg",
          description: "This is product 15",
          category: "Category 3",
        },
        {
          id: 16,
          name: "Product 16,",
          price: 130.99,
          quantity: 130,
          url: "images/products/16.jpg",
          img: "/images/16.jpg",
          description: "This is product 16",
          category: "Category 3",
        },
        {
          id: 17,
          name: "Product 17",
          price: 130.99,
          quantity: 130,
          url: "images/products/17.jpg",
          img: "/images/17.jpg",
          description: "This is product 17",
          category: "Category 3",
        },
        {
          id: 18,
          name: "Product 18",
          price: 130.99,
          quantity: 130,
          url: "images/products/18.jpg",
          img: "/images/18.jpg",
          description: "This is product 18",
          category: "Category 3",
        },
        {
          id: 19,
          name: "Product 19",
          price: 130.99,
          quantity: 130,
          url: "images/products/19.jpg",
          img: "/images/19.jpg",
          description: "This is product 19",
          category: "Category 3",
        },
        {
          id: 20,
          name: "Product 20",
          price: 130.99,
          quantity: 130,
          url: "images/products/20.jpg",
          img: "/images/20.jpg",
          description: "This is product 20",
          category: "Category 3",
        },
        {
          id: 21,
          name: "Product 21",
          price: 130.99,
          quantity: 130,
          url: "images/products/21.jpg",
          img: "/images/21.jpg",
          description: "This is product 21",
          category: "Category 3",
        },
        {
          id: 22,
          name: "Product 22",
          price: 130.99,
          quantity: 130,
          url: "images/products/22.jpg",
          img: "/images/22.jpg",
          description: "This is product 22",
          category: "Category 3",
        },
        {
          id: 23,
          name: "Product 23",
          price: 130.99,
          quantity: 130,
          url: "images/products/23.jpg",
          img: "/images/23.jpg",
          description: "This is product 23",
          category: "Category 3",
        },
        {
          id: 24,
          name: "Product 24",
          price: 130.99,
          quantity: 130,
          url: "images/products/24.jpg",
          img: "/images/24.jpg",
          description: "This is product 24",
          category: "Category 3",
        },
        {
          id: 25,
          name: "Product 25",
          price: 530.99,
          quantity: 130,
          url: "images/products/29.jpg",
          img: "/images/29.jpg",
          description: "This is product 25",
          category: "Category 3",
        },
        {
          id: 26,
          name: "Product 26",
          price: 160.99,
          quantity: 130,
          url: "images/products/31.jpg",
          img: "/images/31.jpg",
          description: "This is product 26",
          category: "Category 3",
        },
        {
          id: 27,
          name: "Product 27",
          price: 140.99,
          quantity: 130,
          url: "images/products/32.jpg",
          img: "/images/32.jpg",
          description: "This is product 26",
          category: "Category 3",
        },
        {
          id: 28,
          name: "Product 28",
          price: 170.99,
          quantity: 130,
          url: "images/products/33.jpg",
          img: "/images/33.jpg",
          description: "This is product 27",
          category: "Category 3",
        },
        {
          id: 29,
          name: "Product 29",
          price: 190.99,
          quantity: 130,
          url: "images/products/34.jpg",
          img: "/images/34.jpg",
          description: "This is product 28",
          category: "Category 3",
        },
        {
          id: 30,
          name: "Product 30",
          price: 200.99,
          quantity: 140,
          url: "images/products/30.jpg",
          img: "/images/30.jpg",
          description: "This is product 30",
          category: "Category 1",
        },
        {
          id: 31,
          name: "Product 31",
          price: 210.99,
          quantity: 150,
          url: "images/products/31.jpg",
          img: "/images/31.jpg",
          description: "This is product 31",
          category: "Category 2",
        },
        {
          id: 32,
          name: "Product 32",
          price: 220.99,
          quantity: 160,
          url: "images/products/32.jpg",
          img: "/images/32.jpg",
          description: "This is product 32",
          category: "Category 3",
        },
        {
          id: 33,
          name: "Product 33",
          price: 230.99,
          quantity: 170,
          url: "images/products/33.jpg",
          img: "/images/33.jpg",
          description: "This is product 33",
          category: "Category 1",
        },
        {
          id: 34,
          name: "Product 34",
          price: 240.99,
          quantity: 180,
          url: "images/products/34.jpg",
          img: "/images/34.jpg",
          description: "This is product 34",
          category: "Category 2",
        },
        {
          id: 35,
          name: "Product 35",
          price: 250.99,
          quantity: 190,
          url: "images/products/35.jpg",
          img: "/images/35.jpg",
          description: "This is product 35",
          category: "Category 3",
        },
        {
          id: 36,
          name: "Product 36",
          price: 260.99,
          quantity: 200,
          url: "images/products/36.jpg",
          img: "/images/36.jpg",
          description: "This is product 36",
          category: "Category 1",
        },
        {
          id: 37,
          name: "Product 37",
          price: 270.99,
          quantity: 210,
          url: "images/products/37.jpg",
          img: "/images/37.jpg",
          description: "This is product 37",
          category: "Category 2",
        },
        {
          id: 38,
          name: "Product 38",
          price: 280.99,
          quantity: 220,
          url: "images/products/38.jpg",
          img: "/images/38.jpg",
          description: "This is product 38",
          category: "Category 3",
        },
        {
          id: 39,
          name: "Product 39",
          price: 290.99,
          quantity: 230,
          url: "images/products/39.jpg",
          img: "/images/39.jpg",
          description: "This is product 39",
          category: "Category 1",
        },
        {
          id: 40,
          name: "Product 40",
          price: 300.99,
          quantity: 240,
          url: "images/products/40.jpg",
          img: "/images/40.jpg",
          description: "This is product 40",
          category: "Category 2",
        },
        {
          id: 41,
          name: "Product 41",
          price: 310.99,
          quantity: 250,
          url: "images/products/41.jpg",
          img: "/images/41.jpg",
          description: "This is product 41",
          category: "Category 3",
        },
        {
          id: 42,
          name: "Product 42",
          price: 320.99,
          quantity: 260,
          url: "images/products/42.jpg",
          img: "/images/42.jpg",
          description: "This is product 42",
          category: "Category 1",
        },
        {
          id: 43,
          name: "Product 43",
          price: 330.99,
          quantity: 270,
          url: "images/products/43.jpg",
          img: "/images/43.jpg",
          description: "This is product 43",
          category: "Category 2",
        },
        {
          id: 44,
          name: "Product 44",
          price: 340.99,
          quantity: 280,
          url: "images/products/44.jpg",
          img: "/images/44.jpg",
          description: "This is product 44",
          category: "Category 3",
        },
        {
          id: 45,
          name: "Product 45",
          price: 350.99,
          quantity: 290,
          url: "images/products/45.jpg",
          img: "/images/45.jpg",
          description: "This is product 45",
          category: "Category 1",
        },
        {
          id: 46,
          name: "Product 46",
          price: 360.99,
          quantity: 300,
          url: "images/products/46.jpg",
          img: "/images/46.jpg",
          description: "This is product 46",
          category: "Category 2",
        },
        {
          id: 47,
          name: "Product 47",
          price: 370.99,
          quantity: 310,
          url: "images/products/47.jpg",
          img: "/images/47.jpg",
          description: "This is product 47",
          category: "Category 3",
        },
        {
          id: 48,
          name: "Product 48",
          price: 380.99,
          quantity: 320,
          url: "images/products/48.jpg",
          img: "/images/48.jpg",
          description: "This is product 48",
          category: "Category 1",
        },
        {
          id: 49,
          name: "Product 49",
          price: 390.99,
          quantity: 330,
          url: "images/products/49.jpg",
          img: "/images/49.jpg",
          description: "This is product 49",
          category: "Category 2",
        },
        {
          id: 50,
          name: "Product 50",
          price: 400.99,
          quantity: 340,
          url: "images/products/50.jpg",
          img: "/images/50.jpg",
          description: "This is product 50",
          category: "Category 3",
        },
        {
          id: 51,
          name: "Product 51",
          price: 410.99,
          quantity: 350,
          url: "images/products/51.jpg",
          img: "/images/51.jpg",
          description: "This is product 51",
          category: "Category 1",
        },
        {
          id: 52,
          name: "Product 52",
          price: 420.99,
          quantity: 360,
          url: "images/products/52.jpg",
          img: "/images/52.jpg",
          description: "This is product 52",
          category: "Category 2",
        },
        {
          id: 53,
          name: "Product 53",
          price: 430.99,
          quantity: 370,
          url: "images/products/53.jpg",
          img: "/images/53.jpg",
          description: "This is product 53",
          category: "Category 3",
        },
        {
          id: 54,
          name: "Product 54",
          price: 440.99,
          quantity: 380,
          url: "images/products/54.jpg",
          img: "/images/54.jpg",
          description: "This is product 54",
          category: "Category 1",
        },
        {
          id: 55,
          name: "Product 55",
          price: 450.99,
          quantity: 390,
          url: "images/products/55.jpg",
          img: "/images/55.jpg",
          description: "This is product 55",
          category: "Category 2",
        },
        {
          id: 56,
          name: "Product 56",
          price: 460.99,
          quantity: 400,
          url: "images/products/56.jpg",
          img: "/images/56.jpg",
          description: "This is product 56",
          category: "Category 3",
        },
        {
          id: 57,
          name: "Product 57",
          price: 470.99,
          quantity: 410,
          url: "images/products/57.jpg",
          img: "/images/57.jpg",
          description: "This is product 57",
          category: "Category 1",
        },
        {
          id: 58,
          name: "Product 58",
          price: 480.99,
          quantity: 420,
          url: "images/products/58.jpg",
          img: "/images/58.jpg",
          description: "This is product 58",
          category: "Category 2",
        },
        {
          id: 59,
          name: "Product 59",
          price: 490.99,
          quantity: 430,
          url: "images/products/59.jpg",
          img: "/images/59.jpg",
          description: "This is product 59",
          category: "Category 3",
        },
        {
          id: 60,
          name: "Product 60",
          price: 500.99,
          quantity: 440,
          url: "images/products/60.jpg",
          img: "/images/60.jpg",
          description: "This is product 60",
          category: "Category 1",
        },
      ],
    },
  ],
};

export default products;
